server:
  port: 10002
spring:
  application:
    name: agent-search
  config:
    import:
      - classpath:config/search_agent.yml
      - classpath:config/dashscope.yml
      - classpath:config/a2a.yml
      - classpath:config/mcp.yml
