server:
  port: 10001
spring:
  application:
    name: agent-memory
  config:
    import:
      - classpath:config/memory_agent.yml
      - classpath:config/dashscope.yml
      - classpath:config/a2a.yml
      - classpath:config/mcp.yml
