spring:
  ai:
    mcp:
      client:
        sse:
          connections:
            WebSearch:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/WebSearch/sse
            amap-maps:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/amap-maps/sse
            china-railway:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/china-railway/sse
