server:
  port: 8000
spring:
  application:
    name: agent-plan
  config:
    import:
      - classpath:config/dashscope.yml
      - classpath:config/a2a.yml
      - classpath:config/mcp.yml
      - classpath:config/search_agent.yml
      - classpath:config/railway_agent.yml
