server:
  port: 9001
spring:
  application:
    name: mcp-weather
  ai:
    mcp:
      server:
        name: mcp-weather
        version: 1.0.0
        type: SYNC
        instructions: "该MCP服务提供天气信息"
    alibaba:
      mcp:
        nacos:
          register:
            enabled: true
          server-addr: ${NACOS_ADDRESS:localhost:8848}
          namespace: ${NACOS_NAMESPACE:public}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD:123456}
