server:
  port: 10003
spring:
  application:
    name: agent-chat
  config:
    import:
      - classpath:config/chat_agent.yml
      - classpath:config/dashscope.yml
      - classpath:config/a2a.yml
