spring:
  ai:
    alibaba:
      a2a:
        nacos:
          server-addr: ${NACOS_ADDRESS:localhost:8848}
          namespace: ${NACOS_NAMESPACE:public}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD:123456}
        server:
          version: 1.0.0
          card:
            name: memory_agent
            description: 能够对用户历史行为进行分析和记忆
