server:
  port: 8000
spring:
  application:
    name: ai-client
  ai:
    alibaba:
      a2a:
        nacos:
          discovery:
            enabled: true
          server-addr: ${NACOS_ADDRESS:localhost:8848}
          namespace: ${NACOS_NAMESPACE:public}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD:123456}