server:
  port: 9999
spring:
  application:
    name: agent-alibaba
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-max
    alibaba:
      a2a:
        nacos:
          server-addr: ${NACOS_ADDRESS:localhost:8848}
          namespace: ${NACOS_NAMESPACE:public}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD:123456}
        server:
          version: 1.0.0
      mcp:
        nacos:
          server-addr: ${NACOS_ADDRESS:localhost:8848}
          namespace: ${NACOS_NAMESPACE:public}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD:123456}
          client:
            enabled: true
            sse:
              connections:
                server1:
                  service-name: mcp-weather
                  version: 1.0.0
